name: Compilar Batocera Customizado
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Baixar o código do repositório com submódulos
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # Isso garante que o Buildroot e as dependências sejam baixados!

    - name: Instalar dependências completas do Buildroot
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential sed make binutils patch gzip bzip2 perl tar cpio unzip rsync file bc wget libncurses5-dev libssl-dev cvs git mercurial subversion bash python3-dev syslinux-utils

    - name: Configurar e Compilar Batocera
      run: |
        make batocera-x86_64_defconfig
        make linux-rebuild
        make
